# Introduction

`r if(identical(gitbook_on, FALSE)) knitr::asis_output(paste0("This report is available as a PDF and as an online interactive report at ", ngr::ngr_str_link_url(url_base = params$report_url, anchor_text = params$report_url), ". We recommend viewing online as the web-hosted HTML version contains more features and is more easily navigable. Please reference the website for the latest PDF from ", ngr::ngr_str_link_url(url_base = params$repo_url, url_resource = "raw/main/docs/fish_passage_peace_2024_reporting.pdf", anchor_text = "fish_passage_peace_2024_reporting.pdf"), "."))`

`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which
provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing
habitat [@bramblett_etal2002SeasonalUse; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can
present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the
culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road
crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by
ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation
designs.

<br>

The Society for Ecosystem Restoration in Northern BC (SERNbc) is working together with the McLeod Lake Indian Band, the
Peace Region Fish and Wildlife Compensation Program (FWCP), the Provincial Fish Passage Technical Working Group (FPTWG),
road/rail tenure holders and other stakeholders/partners to prioritize, plan and fund the restoration of fish
passage at road crossing structure barriers within the Parsnip River, Carp River and Crooked River watershed groups.

<br>

This project builds on Society for Ecosystem Restoration Northern BC (SERNbc) work in:


- [Parsnip River Watershed – Fish Habitat Confirmations (PEA-F20-F-2967)](https://newgraphenvironment.github.io/Parsnip_Fish_Passage/){target="_blank"} [@irvine2020ParsnipRiver]
- [PEA-F22-F-3577-DCA Restoring Fish Passage in the Peace Region](https://www.newgraphenvironment.com/fish_passage_parsnip_2021_reporting/){target="_blank"} [@irvine2022PEAF22F3577DCARestoring]  
- [Restoring Fish Passage in the Peace Region - 2022 - PEA-F23-F-3761-DCA](https://newgraphenvironment.github.io/fish_passage_peace_2022_reporting/){target="_blank"} [@irvine_winterscheidt2023RestoringFish]  
- [Restoring Fish Passage in the Peace Region - 2023](https://newgraphenvironment.github.io/fish_passage_peace_2023_reporting/){target="_blank"} [@irvine_winterscheidt2024RestoringFish]


<br>

Through this year's project activities (2024/2025) we engaged numerous project partners and were able to identify, complete and
catalyze fish passage restoration activities at multiple priority sites. 

<br>

Through the ongoing development of open source analysis, data presentation and project collaboration tools we are 
identifying new restoration opportunities, clarifying restoration benefits, communicating with the broader community and 
implementing on the ground works. 

<br>

This document can be considered a living document. Version numbers are logged for each release with modifications, enhancements, and other changes tracked in the [Changelog](#changelog) with issues and proposed/planned enhancements tracked `r ngr::ngr_str_link_url(url_base = params$repo_url, url_resource = "issues", anchor_text = "here")`.

