# =============================================================================
# Climate departure inputs snapshot — pull cached cd outputs from the cd
# package's inst/ directories into data/gis/cd_peace* so the Peace report
# builds cleanly without a live cd pipeline run.
#
# Self-containment principle (issue #16):
#   The cd package runs the ERA5-Land pipeline and caches region-level
#   outputs in inst/vignette-data/ and inst/extdata/. This script copies
#   those cached files here under the cd_peace_ prefix. The appendix
#   still needs library(cd) at render time for plotting/summary helpers
#   (cd::cd_plot_timeseries, cd::cd_compare, etc.) but does NOT need
#   a live S3 connection or ERA5 fetch.
#
# Refresh procedure (when cd package outputs are updated):
#   1. In the cd repo:
#        - re-run the pipeline (vignettes/peace-fwcp.Rmd or data-raw/)
#        - commit + push refreshed inst/ files
#        - bump cd version + push tag
#   2. In this repo:
#        - pak::pak("NewGraphEnvironment/cd") to update the package
#        - source('scripts/cd_inputs_snapshot.R')
#        - inspect data/cd_inputs_snapshot_manifest.txt diff
#        - commit the refreshed inputs
#
# Requires: cd >= 0.3.0 (cd::cd_compare() defaults added in v0.3.0)
# =============================================================================

library(sf)

cd_ver <- packageVersion("cd")
if (cd_ver < "0.3.0") {
  stop("cd >= 0.3.0 required (installed: ", cd_ver, "). ",
       "Run pak::pak('NewGraphEnvironment/cd') to update.")
}

out_dir <- file.path("data", "gis")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

MANIFEST <- "data/cd_inputs_snapshot_manifest.txt"

# ---- 1. Merge two source gpkgs into single cd_peace.gpkg -------------------

gpkg_out <- file.path(out_dir, "cd_peace.gpkg")
if (file.exists(gpkg_out)) file.remove(gpkg_out)

aoi_src <- system.file("extdata", "example_aoi_fwcp_peace.gpkg",
                        package = "cd", mustWork = TRUE)
ctx_src <- system.file("extdata", "context_fwcp_peace.gpkg",
                        package = "cd", mustWork = TRUE)

write_layer <- function(x, layer) {
  sf::st_write(x, gpkg_out, layer = layer, delete_layer = TRUE,
               append = TRUE, quiet = TRUE)
}

message("Reading aoi from ", basename(aoi_src), " ...")
aoi <- sf::st_read(aoi_src, quiet = TRUE)
write_layer(aoi, "aoi")

ctx_layers <- sf::st_layers(ctx_src)$name
message("Reading ", length(ctx_layers), " context layers from ",
        basename(ctx_src), " ...")
for (lyr in ctx_layers) {
  d <- sf::st_read(ctx_src, layer = lyr, quiet = TRUE)
  write_layer(d, lyr)
  message("  ", lyr, ": ", nrow(d), " features")
}

# ---- 2. Copy flat files ----------------------------------------------------

FLAT_FILES <- list(
  list(src = system.file("vignette-data", "peace_fwcp.rds",
                          package = "cd", mustWork = TRUE),
       dst = file.path(out_dir, "cd_peace.rds")),
  list(src = system.file("vignette-data", "peace_fwcp_departure_tmean.tif",
                          package = "cd", mustWork = TRUE),
       dst = file.path(out_dir, "cd_peace_departure_tmean.tif")),
  list(src = system.file("extdata", "peace_wsg_ecoregion_commentary.csv",
                          package = "cd", mustWork = TRUE),
       dst = file.path(out_dir, "cd_peace_wsg_ecoregion.csv"))
)

copied <- character(0)
for (f in FLAT_FILES) {
  file.copy(f$src, f$dst, overwrite = TRUE)
  copied <- c(copied, f$dst)
  message("Copied: ", basename(f$src), " -> ", f$dst)
}

# ---- 3. Write manifest -----------------------------------------------------

all_outputs <- c(gpkg_out, vapply(FLAT_FILES, `[[`, character(1), "dst"))

manifest_lines <- c(
  "# Climate departure inputs snapshot manifest",
  paste0("# Generated by scripts/cd_inputs_snapshot.R on ",
         format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  "",
  paste0("cd_version:     ", as.character(cd_ver)),
  paste0("snapshotted_at: ", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z")),
  "",
  paste0("gpkg_layers:    ",
         paste(c("aoi", ctx_layers), collapse = ", ")),
  "",
  "files:"
)
for (fp in all_outputs) {
  manifest_lines <- c(
    manifest_lines,
    sprintf("  - path: %s", fp),
    sprintf("    md5:  %s", unname(tools::md5sum(fp)))
  )
}
writeLines(manifest_lines, MANIFEST)

# ---- 4. Report -------------------------------------------------------------

cat("=== Climate departure inputs snapshot ===\n")
cat(sprintf("cd package:  %s\n", cd_ver))
cat(sprintf("gpkg layers: %s\n",
            paste(sf::st_layers(gpkg_out)$name, collapse = ", ")))
for (fp in all_outputs) {
  cat(sprintf("  %-45s %.2f MB\n", basename(fp),
              file.info(fp)$size / 1024^2))
}
cat(sprintf("Manifest:    %s\n", MANIFEST))
