---
title: "0110-photos-resize"
date: "Created: 2024-10-21 | Updated: `r format(Sys.Date(), '%Y-%m-%d')`"
output: 
  html_document:
    code_folding: "hide"
params:
  repo_owner: "NewGraphEnvironment"
  repo_name: "fish_passage_peace_2024_reporting"
  gis_name: "sern_peace_fwcp_2023"
  job_name: "2024-073-sern-peace-fish-passage"
---


```{r setup, echo=TRUE, include = TRUE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, dpi=60, out.width = "100%", eval = FALSE)
options(scipen=999)
options(knitr.kable.NA = '--') #'--'
options(knitr.kable.NAN = '--')
```



```{r}
# grab the files from mergin and move to project using linux cmd
# mv -v ~/Projects/gis/mergin/bcfishpass_elkr_20220904/photos/* ~/Projects/current/2022-056-nupqu-elk-cwf/data/photos/mergin/originals
# mv -v ~/Projects/gis/mergin/bcfishpass_skeena_20220823-v225/photos/* ~/Projects/current/2022-049-sern-skeena-fish-passage/data/photos/mergin/

# Build Local Directory  ------------------------------------------------------------
dir_photos_mergin_raw <- fs::path(path.expand('~/'), "Projects/gis/", params$gis_name, "/ignore_mobile/photos/")
dir_photos_mergin_resized <- fs::path(path.expand('~/'), "Projects/gis/", params$gis_name, "/ignore_mobile/photos_resized/")
# dir_photos_processed_final <- fs::path(path.expand('~/'), "Projects/data/", params$gis_name, "/photos/")
dir_photos_originals <- fs::path(path.expand('~/'), "Library/CloudStorage/OneDrive-Personal/Projects", params$job_name, "/data/photos/")
dir_photos_onedrive <- fs::path(path.expand('~/'), "Library/CloudStorage/OneDrive-Personal/Projects", params$job_name, "photos/")

# we are going to resize the original photos and move them to onedrive just in case we need to do homework
fs::dir_create(fs::path(dir_photos_onedrive, "ai"), recurse = TRUE)
fs::dir_create(fs::path(dir_photos_onedrive, "ls"), recurse = TRUE)

fpr_photo_resize_batch(
  dir_source = fs::path(dir_photos_originals,"ai/originals"),
  dir_target = fs::path(dir_photos_onedrive, "ai")
)

fpr_photo_resize_batch(
  dir_source = fs::path(dir_photos_originals,"ls/originals"),
  dir_target = fs::path(dir_photos_onedrive, "ls")
)



# QGIS mergin photos-----------------------------------------------------------------------------------------------------
## Clean up the mergin file----------------------------------------------------------------------------------------------------
# remove photos.txt file included in project when created (was to allow mergin git to see the photos dir) but needs
# to be removed or ignored to not break fpr_photo_resize_batch
fs::file_delete(
  fs::path(dir_photos_mergin_raw, "/photos.txt")
)

## Resize----------------------------------------------------------------------------------------------------
# resize the photos and change the extension to JPG for consistency and to avoid issues with fpr_photo calls in reporting
# sync to mergin after copying to new dir (resized) and removing originals
# record version number of mergin project in issue for now to track

# get a list of the photos
p <- fs::dir_ls(dir_photos_mergin_raw, recurse = T)


# see how large the photos are in MB rounded to 1 decimal using purrr
s <- p %>%
  purrr::map(file.info) %>%
  purrr::map_dbl("size")/1024/1024

# identify the range of sizes
range(s)
# [1] 0.06309891 0.57638550 Not bad.  Lets resize anyway so that we know they fit the reporting

# create the target directory
fs::dir_create(dir_photos_mergin_resized, recurse = TRUE)

fpr_photo_resize_batch(
  dir_source = dir_photos_mergin_raw,
  dir_target = fs::path(dir_photos_mergin_resized)
)

# quick check to see if the photos are all accounted for
identical(
  length(
    fs::dir_ls(dir_photos_mergin_raw, recurse = T)),
  length(
    fs::dir_ls(dir_photos_mergin_resized, recurse = T))
)

# erase all the photos in the original directory
file.remove(
  fs::dir_ls(dir_photos_mergin_raw, recurse = T)
)

# recreate the photos.txt file so the form still works
file.create(
  fs::path(dir_photos_mergin_raw, "photos.txt")
)




########################################################################################################################
# Rename the photos and sort into directories -----------------------------------------------------------------------------------------------------


form_pscis_photos_raw <- sf::st_read(
  dsn = fs::path('../../gis/', params$gis_name, '/data_field/2023/form_pscis_2023.gpkg')) %>%
  arrange(site_id)

# check for duplicate sites
form_pscis_photos_raw %>%
  dplyr::filter(!is.na(site_id)) %>%
  group_by(site_id) %>%
  dplyr::filter(n()>1) %>%
  nrow()

# check for empty sites
form_pscis_photos_raw %>%
  dplyr::filter(is.na(site_id)) %>%
  nrow()

# create site photo directories right on mergin to make them easy to share...
form_pscis_photos_raw %>%
  pull(site_id) %>%
  as.character() %>%
  purrr::map(
    fpr::fpr_photo_folders, path = dir_photos_mergin_raw
  )

# NOTE - accidentally didn't save the actual workflow for this so this may not be exactly what I did
fpr::fpr_photo_rename(
  dat = form_pscis_photos_raw,
  dir_from_stub = dir_photos_mergin_resized,
  dir_to_stub = dir_photos_mergin_raw
)

# looks like 9900446 has no photos at all with no note of it in the comments... Not sure what to do about that
qa_missing <- fpr_photo_qa_missing_all(
  dat = form_pscis_photos_raw,
  dir_photos = dir_photos_mergin_raw
) %>%
  pull(site)

qa_all <- fpr::fpr_photo_qa(
  dat = form_pscis_photos_raw,
  dir_photos = dir_photos_mergin_raw
) %>%
  data.table::rbindlist(fill = TRUE)

qa <- fpr_photo_qa_df(
  dat = form_pscis_photos_raw,
  dir_photos = dir_photos_mergin_raw
)

# here is the test for missing individual photos
test <- fpr::fpr_photo_qa() %>%
  bind_rows() %>%
  dplyr::filter(if_any(everything(), is.na))



################################################################################################################
#--------------------------------------------------Simpc---------------------------------------------------
################################################################################################################


# Build Local Directory  ------------------------------------------------------------
dir_project <- 'sern_simpcw_2023'
dir_job_id <- '2023-065-sern-capacity'
dir_photos_mergin_raw <- fs::path(path.expand('~/'), "Projects/gis/", params$gis_name, "/ignore_mobile/photos/")
dir_photos_mergin_resized <- fs::path(path.expand('~/'), "Projects/gis/", params$gis_name, "/ignore_mobile/photos_resized/")
# dir_photos_processed_final <- fs::path(path.expand('~/'), "Projects/data/", params$gis_name, "/photos/")
dir_photos_originals <- fs::path(path.expand('~/'), "Library/CloudStorage/OneDrive-Personal/Projects", params$gis_name, "/fraser/data/photos/")
dir_photos_onedrive <- fs::path(path.expand('~/'), "Library/CloudStorage/OneDrive-Personal/Projects", params$job_name, "photos/")


# QGIS mergin photos-----------------------------------------------------------------------------------------------------
## Clean up the mergin file----------------------------------------------------------------------------------------------------
# remove photos.txt file included in project when created (was to allow mergin git to see the photos dir) but needs
# to be removed or ignored to not break fpr_photo_resize_batch
fs::file_delete(
  fs::path(dir_photos_mergin_raw, "/photos.txt")
)

## Resize----------------------------------------------------------------------------------------------------
# resize the photos and change the extension to JPG for consistency and to avoid issues with fpr_photo calls in reporting
# sync to mergin after copying to new dir (resized) and removing originals
# record version number of mergin project in issue for now to track

# get a list of the photos
p <- fs::dir_ls(dir_photos_mergin_raw, recurse = T)


# see how large the photos are in MB rounded to 1 decimal using purrr
s <- p |>
  purrr::map(file.info) |>
  purrr::map_dbl("size")/1024/1024

# identify the range of sizes
range(s)
# [1] 0.2178898 7.3512239 HUUUUGGGGEEE.  Lets resize

# create the target directory
fs::dir_create(dir_photos_mergin_resized, recurse = TRUE)

fpr_photo_resize_batch(
  dir_source = dir_photos_mergin_raw,
  dir_target = fs::path(dir_photos_mergin_resized)
)

# quick check to see if the photos are all accounted for
identical(
  length(
    fs::dir_ls(dir_photos_mergin_raw, recurse = T)),
  length(
    fs::dir_ls(dir_photos_mergin_resized, recurse = T))
)

# erase all the photos in the original directory
file.remove(
  fs::dir_ls(dir_photos_mergin_raw, recurse = T)
)

# recreate the photos.txt file so the form still works
file.create(
  fs::path(dir_photos_mergin_raw, "photos.txt")
)




########################################################################################################################
# Rename the photos and sort into directories -----------------------------------------------------------------------------------------------------
path <- "~/Projects/gis/sern_simpcw_2023/data_field/2023/form_pscis_2023.gpkg"
# here we assume all sites were comleted digitally. Should confirm...
form_pscis_photos_raw <- fpr::fpr_sp_gpkg_backup(
  path_gpkg = path,
  update_utm = TRUE,
  update_site_id = TRUE,
  write_back_to_path = FALSE,
  write_to_csv = FALSE,
  write_to_rdata = FALSE,
  return_object = TRUE)


# # here we assume all sites were completed digitally. Should confirm...
# form_pscis_photos_raw <- sf::st_read(
#   dsn = fs::path('../../gis/', params$gis_name, '/data_field/2023/form_pscis_2023.gpkg')) %>%
#   arrange(site_id)

# check for duplicate sites
form_pscis_photos_raw %>%
  dplyr::filter(!is.na(site_id)) %>%
  group_by(site_id) %>%
  dplyr::filter(n()>1) |>
  nrow()

# check for empty sites
form_pscis_photos_raw %>%
  dplyr::filter(is.na(site_id)) %>%
  nrow()

# create site photo directories right on mergin to make them easy to share...
form_pscis_photos_raw %>%
  pull(site_id) %>%
  as.character() %>%
  purrr::map(
    fpr::fpr_photo_folders, path = dir_photos_mergin_raw
  )

# rename the photos
fpr::fpr_photo_rename(
  dat = form_pscis_photos_raw,
  dir_from_stub = dir_photos_mergin_resized,
  dir_to_stub = dir_photos_mergin_raw
)

# QA
fpr::fpr_photo_qa_df(dat = form_pscis_photos_raw, dir_photos = dir_photos_mergin_raw)


fpr_photo_qa_missing_all(
  dat = form_pscis_photos_raw,
  dir_photos = dir_photos_mergin_raw
)

# before we nuke the resized folder we should compare that all the photos in the resized directory are accounted for
# this was not done but should be.  setdiff with a list of file names starting with the resized directory should work
# to identify any missing photos
setdiff(
  fs::dir_ls(dir_photos_mergin_resized, recurse = T),
  fs::dir_ls(dir_photos_mergin_raw, recurse = T)
)

fs::dir_delete(dir_photos_mergin_resized)
```

